export { MeshDraft } from "./draft";
export {
  addFace,
  addVertex,
  allocateId,
  attributeStoreKey,
  canonicalEdgeVertices,
  cloneAttributeValue,
  cloneMeshState,
  createMeshState,
  domainMap,
  edgePairKey,
  elementMap,
  faceVertices,
  mergeAllocatorHistory,
  rebuildIndexes,
  removeFace,
  removeVertex,
  replaceFaceVertices,
  reserveExistingId,
  restoreState,
  retireId,
  setAttributeValue,
  setVertexPosition,
} from "./state";
export type {
  CreatedFaceRecords,
  ElementDomain,
  IdAllocatorState,
  MeshState,
  MutableAttributeStore,
  MutableCornerRecord,
  MutableEdgeRecord,
  MutableFaceRecord,
  MutableVertexRecord,
  RemovedElementIds,
} from "./types";
export { assertValidTopology, validateTopology } from "./validator";
